// Code generated by entc, DO NOT EDIT.

package runtime

import (
	"test/ent/schema"
	"test/ent/testmodel"
	"time"

	"github.com/gofrs/uuid"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	testmodelMixin := schema.TestModel{}.Mixin()
	testmodelHooks := schema.TestModel{}.Hooks()
	testmodel.Hooks[0] = testmodelHooks[0]
	testmodelMixinFields0 := testmodelMixin[0].Fields()
	testmodelMixinFields1 := testmodelMixin[1].Fields()
	testmodelFields := schema.TestModel{}.Fields()
	_ = testmodelFields
	// testmodelDescCreateTime is the schema descriptor for create_time field.
	testmodelDescCreateTime := testmodelMixinFields1[0].Descriptor()
	// testmodel.DefaultCreateTime holds the default value on creation for the create_time field.
	testmodel.DefaultCreateTime = testmodelDescCreateTime.Default.(func() time.Time)
	// testmodelDescUpdateTime is the schema descriptor for update_time field.
	testmodelDescUpdateTime := testmodelMixinFields1[1].Descriptor()
	// testmodel.DefaultUpdateTime holds the default value on creation for the update_time field.
	testmodel.DefaultUpdateTime = testmodelDescUpdateTime.Default.(func() time.Time)
	// testmodel.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	testmodel.UpdateDefaultUpdateTime = testmodelDescUpdateTime.UpdateDefault.(func() time.Time)
	// testmodelDescID is the schema descriptor for id field.
	testmodelDescID := testmodelMixinFields0[0].Descriptor()
	// testmodel.DefaultID holds the default value on creation for the id field.
	testmodel.DefaultID = testmodelDescID.Default.(func() uuid.UUID)
}

const (
	Version = "v0.4.2"                                          // Version of ent codegen.
	Sum     = "h1:JzU5dYJH9XdjfIKgOiPPK3szkqLqcdPWgVder4Ogows=" // Sum of ent codegen.
)
