// Code generated by entc, DO NOT EDIT.

package runtime

import (
	"test/ent/schema"
	"test/ent/testmodel"

	"github.com/gofrs/uuid"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	testmodelHooks := schema.TestModel{}.Hooks()
	testmodel.Hooks[0] = testmodelHooks[0]
	testmodelFields := schema.TestModel{}.Fields()
	_ = testmodelFields
	// testmodelDescID is the schema descriptor for id field.
	testmodelDescID := testmodelFields[0].Descriptor()
	// testmodel.DefaultID holds the default value on creation for the id field.
	testmodel.DefaultID = testmodelDescID.Default.(func() uuid.UUID)
}

const (
	Version = "v0.4.2"                                          // Version of ent codegen.
	Sum     = "h1:JzU5dYJH9XdjfIKgOiPPK3szkqLqcdPWgVder4Ogows=" // Sum of ent codegen.
)
