// Code generated by entc, DO NOT EDIT.

package testmodel

import (
	"github.com/facebook/ent"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the testmodel type in the database.
	Label = "test_model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTest holds the string denoting the test field in the database.
	FieldTest = "test"

	// Table holds the table name of the testmodel in the database.
	Table = "test_models"
)

// Columns holds all SQL columns for testmodel fields.
var Columns = []string{
	FieldID,
	FieldTest,
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "test/ent/runtime"
//
var (
	Hooks [1]ent.Hook
	// DefaultID holds the default value on creation for the id field.
	DefaultID func() uuid.UUID
)
