// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"test/ent/predicate"
	"test/ent/testmodel"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/google/uuid"
)

// TestModelQuery is the builder for querying TestModel entities.
type TestModelQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.TestModel
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (tmq *TestModelQuery) Where(ps ...predicate.TestModel) *TestModelQuery {
	tmq.predicates = append(tmq.predicates, ps...)
	return tmq
}

// Limit adds a limit step to the query.
func (tmq *TestModelQuery) Limit(limit int) *TestModelQuery {
	tmq.limit = &limit
	return tmq
}

// Offset adds an offset step to the query.
func (tmq *TestModelQuery) Offset(offset int) *TestModelQuery {
	tmq.offset = &offset
	return tmq
}

// Order adds an order step to the query.
func (tmq *TestModelQuery) Order(o ...OrderFunc) *TestModelQuery {
	tmq.order = append(tmq.order, o...)
	return tmq
}

// First returns the first TestModel entity in the query. Returns *NotFoundError when no testmodel was found.
func (tmq *TestModelQuery) First(ctx context.Context) (*TestModel, error) {
	tms, err := tmq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(tms) == 0 {
		return nil, &NotFoundError{testmodel.Label}
	}
	return tms[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tmq *TestModelQuery) FirstX(ctx context.Context) *TestModel {
	tm, err := tmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return tm
}

// FirstID returns the first TestModel id in the query. Returns *NotFoundError when no id was found.
func (tmq *TestModelQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tmq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{testmodel.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (tmq *TestModelQuery) FirstXID(ctx context.Context) uuid.UUID {
	id, err := tmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only TestModel entity in the query, returns an error if not exactly one entity was returned.
func (tmq *TestModelQuery) Only(ctx context.Context) (*TestModel, error) {
	tms, err := tmq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(tms) {
	case 1:
		return tms[0], nil
	case 0:
		return nil, &NotFoundError{testmodel.Label}
	default:
		return nil, &NotSingularError{testmodel.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tmq *TestModelQuery) OnlyX(ctx context.Context) *TestModel {
	tm, err := tmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return tm
}

// OnlyID returns the only TestModel id in the query, returns an error if not exactly one id was returned.
func (tmq *TestModelQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tmq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{testmodel.Label}
	default:
		err = &NotSingularError{testmodel.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tmq *TestModelQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TestModels.
func (tmq *TestModelQuery) All(ctx context.Context) ([]*TestModel, error) {
	if err := tmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tmq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tmq *TestModelQuery) AllX(ctx context.Context) []*TestModel {
	tms, err := tmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return tms
}

// IDs executes the query and returns a list of TestModel ids.
func (tmq *TestModelQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := tmq.Select(testmodel.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tmq *TestModelQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tmq *TestModelQuery) Count(ctx context.Context) (int, error) {
	if err := tmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tmq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tmq *TestModelQuery) CountX(ctx context.Context) int {
	count, err := tmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tmq *TestModelQuery) Exist(ctx context.Context) (bool, error) {
	if err := tmq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tmq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tmq *TestModelQuery) ExistX(ctx context.Context) bool {
	exist, err := tmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tmq *TestModelQuery) Clone() *TestModelQuery {
	return &TestModelQuery{
		config:     tmq.config,
		limit:      tmq.limit,
		offset:     tmq.offset,
		order:      append([]OrderFunc{}, tmq.order...),
		unique:     append([]string{}, tmq.unique...),
		predicates: append([]predicate.TestModel{}, tmq.predicates...),
		// clone intermediate query.
		sql:  tmq.sql.Clone(),
		path: tmq.path,
	}
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TestModel.Query().
//		GroupBy(testmodel.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (tmq *TestModelQuery) GroupBy(field string, fields ...string) *TestModelGroupBy {
	group := &TestModelGroupBy{config: tmq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tmq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.TestModel.Query().
//		Select(testmodel.FieldCreateTime).
//		Scan(ctx, &v)
//
func (tmq *TestModelQuery) Select(field string, fields ...string) *TestModelSelect {
	selector := &TestModelSelect{config: tmq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tmq.sqlQuery(), nil
	}
	return selector
}

func (tmq *TestModelQuery) prepareQuery(ctx context.Context) error {
	if tmq.path != nil {
		prev, err := tmq.path(ctx)
		if err != nil {
			return err
		}
		tmq.sql = prev
	}
	return nil
}

func (tmq *TestModelQuery) sqlAll(ctx context.Context) ([]*TestModel, error) {
	var (
		nodes = []*TestModel{}
		_spec = tmq.querySpec()
	)
	_spec.ScanValues = func() []interface{} {
		node := &TestModel{config: tmq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, tmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tmq *TestModelQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tmq.querySpec()
	return sqlgraph.CountNodes(ctx, tmq.driver, _spec)
}

func (tmq *TestModelQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := tmq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (tmq *TestModelQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   testmodel.Table,
			Columns: testmodel.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: testmodel.FieldID,
			},
		},
		From:   tmq.sql,
		Unique: true,
	}
	if ps := tmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tmq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tmq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tmq *TestModelQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(tmq.driver.Dialect())
	t1 := builder.Table(testmodel.Table)
	selector := builder.Select(t1.Columns(testmodel.Columns...)...).From(t1)
	if tmq.sql != nil {
		selector = tmq.sql
		selector.Select(selector.Columns(testmodel.Columns...)...)
	}
	for _, p := range tmq.predicates {
		p(selector)
	}
	for _, p := range tmq.order {
		p(selector)
	}
	if offset := tmq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tmq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TestModelGroupBy is the builder for group-by TestModel entities.
type TestModelGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tmgb *TestModelGroupBy) Aggregate(fns ...AggregateFunc) *TestModelGroupBy {
	tmgb.fns = append(tmgb.fns, fns...)
	return tmgb
}

// Scan applies the group-by query and scan the result into the given value.
func (tmgb *TestModelGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tmgb.path(ctx)
	if err != nil {
		return err
	}
	tmgb.sql = query
	return tmgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tmgb *TestModelGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := tmgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (tmgb *TestModelGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(tmgb.fields) > 1 {
		return nil, errors.New("ent: TestModelGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := tmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tmgb *TestModelGroupBy) StringsX(ctx context.Context) []string {
	v, err := tmgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (tmgb *TestModelGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tmgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{testmodel.Label}
	default:
		err = fmt.Errorf("ent: TestModelGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tmgb *TestModelGroupBy) StringX(ctx context.Context) string {
	v, err := tmgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (tmgb *TestModelGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(tmgb.fields) > 1 {
		return nil, errors.New("ent: TestModelGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := tmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tmgb *TestModelGroupBy) IntsX(ctx context.Context) []int {
	v, err := tmgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (tmgb *TestModelGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tmgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{testmodel.Label}
	default:
		err = fmt.Errorf("ent: TestModelGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tmgb *TestModelGroupBy) IntX(ctx context.Context) int {
	v, err := tmgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (tmgb *TestModelGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(tmgb.fields) > 1 {
		return nil, errors.New("ent: TestModelGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := tmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tmgb *TestModelGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := tmgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (tmgb *TestModelGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tmgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{testmodel.Label}
	default:
		err = fmt.Errorf("ent: TestModelGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tmgb *TestModelGroupBy) Float64X(ctx context.Context) float64 {
	v, err := tmgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (tmgb *TestModelGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(tmgb.fields) > 1 {
		return nil, errors.New("ent: TestModelGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := tmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tmgb *TestModelGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := tmgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (tmgb *TestModelGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tmgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{testmodel.Label}
	default:
		err = fmt.Errorf("ent: TestModelGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tmgb *TestModelGroupBy) BoolX(ctx context.Context) bool {
	v, err := tmgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tmgb *TestModelGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tmgb.sqlQuery().Query()
	if err := tmgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tmgb *TestModelGroupBy) sqlQuery() *sql.Selector {
	selector := tmgb.sql
	columns := make([]string, 0, len(tmgb.fields)+len(tmgb.fns))
	columns = append(columns, tmgb.fields...)
	for _, fn := range tmgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(tmgb.fields...)
}

// TestModelSelect is the builder for select fields of TestModel entities.
type TestModelSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (tms *TestModelSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := tms.path(ctx)
	if err != nil {
		return err
	}
	tms.sql = query
	return tms.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tms *TestModelSelect) ScanX(ctx context.Context, v interface{}) {
	if err := tms.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (tms *TestModelSelect) Strings(ctx context.Context) ([]string, error) {
	if len(tms.fields) > 1 {
		return nil, errors.New("ent: TestModelSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := tms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tms *TestModelSelect) StringsX(ctx context.Context) []string {
	v, err := tms.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (tms *TestModelSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tms.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{testmodel.Label}
	default:
		err = fmt.Errorf("ent: TestModelSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tms *TestModelSelect) StringX(ctx context.Context) string {
	v, err := tms.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (tms *TestModelSelect) Ints(ctx context.Context) ([]int, error) {
	if len(tms.fields) > 1 {
		return nil, errors.New("ent: TestModelSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := tms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tms *TestModelSelect) IntsX(ctx context.Context) []int {
	v, err := tms.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (tms *TestModelSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tms.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{testmodel.Label}
	default:
		err = fmt.Errorf("ent: TestModelSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tms *TestModelSelect) IntX(ctx context.Context) int {
	v, err := tms.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (tms *TestModelSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(tms.fields) > 1 {
		return nil, errors.New("ent: TestModelSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := tms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tms *TestModelSelect) Float64sX(ctx context.Context) []float64 {
	v, err := tms.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (tms *TestModelSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tms.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{testmodel.Label}
	default:
		err = fmt.Errorf("ent: TestModelSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tms *TestModelSelect) Float64X(ctx context.Context) float64 {
	v, err := tms.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (tms *TestModelSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(tms.fields) > 1 {
		return nil, errors.New("ent: TestModelSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := tms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tms *TestModelSelect) BoolsX(ctx context.Context) []bool {
	v, err := tms.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (tms *TestModelSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tms.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{testmodel.Label}
	default:
		err = fmt.Errorf("ent: TestModelSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tms *TestModelSelect) BoolX(ctx context.Context) bool {
	v, err := tms.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tms *TestModelSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tms.sqlQuery().Query()
	if err := tms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tms *TestModelSelect) sqlQuery() sql.Querier {
	selector := tms.sql
	selector.Select(selector.Columns(tms.fields...)...)
	return selector
}
