// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"test/ent/predicate"
	"test/ent/testmodel"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// TestModelDelete is the builder for deleting a TestModel entity.
type TestModelDelete struct {
	config
	hooks      []Hook
	mutation   *TestModelMutation
	predicates []predicate.TestModel
}

// Where adds a new predicate to the delete builder.
func (tmd *TestModelDelete) Where(ps ...predicate.TestModel) *TestModelDelete {
	tmd.predicates = append(tmd.predicates, ps...)
	return tmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tmd *TestModelDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tmd.hooks) == 0 {
		affected, err = tmd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TestModelMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tmd.mutation = mutation
			affected, err = tmd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tmd.hooks) - 1; i >= 0; i-- {
			mut = tmd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tmd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (tmd *TestModelDelete) ExecX(ctx context.Context) int {
	n, err := tmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tmd *TestModelDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: testmodel.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: testmodel.FieldID,
			},
		},
	}
	if ps := tmd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, tmd.driver, _spec)
}

// TestModelDeleteOne is the builder for deleting a single TestModel entity.
type TestModelDeleteOne struct {
	tmd *TestModelDelete
}

// Exec executes the deletion query.
func (tmdo *TestModelDeleteOne) Exec(ctx context.Context) error {
	n, err := tmdo.tmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{testmodel.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tmdo *TestModelDeleteOne) ExecX(ctx context.Context) {
	tmdo.tmd.ExecX(ctx)
}
