// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// TestModel is the predicate function for testmodel builders.
type TestModel func(*sql.Selector)
